/**
 * Authored by Jared Chan
 **/


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//
//------------------------------------------------------------------------------

// To use ResGen.exe, make two .txt files, each having the same variable names in the same language.
// Assign equivalent translated phrases to the same variables in each .txt file
// Find ResGen.exe in file system, call resgen.exe with cmd prompt and list the .txt file location as 1st param; 2nd param is name of new file (include .resx extension)

// Repeat for the other .txt file

// Take the primary language .resx file and run resgen.exe again but with /str:cs as 2nd param

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class AppResources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal AppResources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppResources", typeof(AppResources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to In alliance with:.
    /// </summary>
    internal static string ABOUT_ALLIANCE {
        get {
            return ResourceManager.GetString("ABOUT-ALLIANCE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to An organization that combines head and heart to strengthen concrete actions towards a resilient, prosperous and inclusive planet based on regeneration.
    ///
    ///Read about our impacts aligned with the Sustainable Development Goals. www.arbolesmagicos.org.
    ///
    ///The colors of tree flowers arouse curiosity allowing learning from their beauty (positive bio-literacy), this App seeks to generate a community that shares and maps those iconic trees to celebrate, enjoy and enjoy them. chase its flowering peak every year. #Flora [rest of string was truncated]&quot;;.
    /// </summary>
    internal static string ABOUT_MAGICAL_TREES_BOTTOM {
        get {
            return ResourceManager.GetString("ABOUT-MAGICAL-TREES-BOTTOM", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Magical Trees is a movement that celebrate the flowering trees like a bridge of regeneration of social and collective wellness..
    /// </summary>
    internal static string ABOUT_MAGICAL_TREES_INTRO {
        get {
            return ResourceManager.GetString("ABOUT-MAGICAL-TREES-INTRO", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Magical Trees is a movement that celebrate the flowering trees like a bridge of regeneration of social and collective wellness.
    ///
    ///Our invitation: The Pause gives us a space to be present, from there we can choose more clearly. By contemplating we restore our attention. When we connect we approach the internal, thus we enhance the collective. And by creating materialize dreams. Head, heart and hands..
    /// </summary>
    internal static string ABOUT_MAGICAL_TREES_TOP {
        get {
            return ResourceManager.GetString("ABOUT-MAGICAL-TREES-TOP", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Magical Trees.
    /// </summary>
    internal static string ABOUT_TITLE {
        get {
            return ResourceManager.GetString("ABOUT-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to What is Magical Trees?.
    /// </summary>
    internal static string ABOUT_WHAT_IS {
        get {
            return ResourceManager.GetString("ABOUT-WHAT-IS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Admin Menu.
    /// </summary>
    internal static string ADMIN_MENU_TITLE {
        get {
            return ResourceManager.GetString("ADMIN-MENU-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Back.
    /// </summary>
    internal static string BACK_BUTTON {
        get {
            return ResourceManager.GetString("BACK-BUTTON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Begin to explore.
    /// </summary>
    internal static string BEGIN_EXPLORING {
        get {
            return ResourceManager.GetString("BEGIN-EXPLORING", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Cancel.
    /// </summary>
    internal static string CANCEL {
        get {
            return ResourceManager.GetString("CANCEL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Nature has a rhythm and a time, which is the present. To reconnect with it, it is essential to be here, focus our attention and channel our potential toward the present moment. &apos;To be here&apos; means synchronizing ourselves with our surroundings.Observing trees in bloom is a way to synchronize our minds with the cycles of nature..
    /// </summary>
    internal static string FDS1 {
        get {
            return ResourceManager.GetString("FDS1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to In a world in which everything happens so quickly, enjoying moments of deceleration helps us to process the stimuli to which we are exposed, validate our path toward a higher purpose, and refresh ourselves spiritually. Slowing down allows us to be present..
    /// </summary>
    internal static string FDS2 {
        get {
            return ResourceManager.GetString("FDS2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Colors stand out in a green forest or urban landscape. They give personality to each tree, attract our attention, and fine-tune our perception both of nature and of ourselves..
    /// </summary>
    internal static string FDS3 {
        get {
            return ResourceManager.GetString("FDS3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The phenomenon of synchronized or mass blooming is a survival mechanism for trees. By blooming at the same time, they ensure that pollinators will focus on them, thus safeguarding the continuity of their species.Some species with this characteristic include cortez amarillo, cortez negro, gallinazo, mayo, poró gigante..
    /// </summary>
    internal static string FDS4 {
        get {
            return ResourceManager.GetString("FDS4", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Communities of practice so passionate in blooming trees. When they see the colors their attention is tuned. People connected to the forest..
    /// </summary>
    internal static string FDS5 {
        get {
            return ResourceManager.GetString("FDS5", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Delete Filter.
    /// </summary>
    internal static string FILTER_DELETE {
        get {
            return ResourceManager.GetString("FILTER-DELETE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to You can only use one filter at a time, please remove the one you are currently using.
    /// </summary>
    internal static string FILTER_ERROR {
        get {
            return ResourceManager.GetString("FILTER-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Filter Shown Reports.
    /// </summary>
    internal static string FILTER_TITLE {
        get {
            return ResourceManager.GetString("FILTER-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Flowering Color.
    /// </summary>
    internal static string FILTER_TREECOLOR {
        get {
            return ResourceManager.GetString("FILTER-TREECOLOR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tree Name.
    /// </summary>
    internal static string FILTER_TREENAME {
        get {
            return ResourceManager.GetString("FILTER-TREENAME", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Flowering Culture.
    /// </summary>
    internal static string FLOWERING_CULTURE_TITLE {
        get {
            return ResourceManager.GetString("FLOWERING-CULTURE-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Forgotten password?.
    /// </summary>
    internal static string FORGOTTEN_PASSWORD {
        get {
            return ResourceManager.GetString("FORGOTTEN-PASSWORD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to We&apos;re going to send you a email to reset your password.
    /// </summary>
    internal static string FORGOTTEN_PASSWORD_MESSAGE {
        get {
            return ResourceManager.GetString("FORGOTTEN-PASSWORD-MESSAGE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Write your email here...
    /// </summary>
    internal static string FORGOTTEN_PASSWORD_PLACEHOLDER {
        get {
            return ResourceManager.GetString("FORGOTTEN-PASSWORD-PLACEHOLDER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Send Verification.
    /// </summary>
    internal static string FORGOTTEN_PASSWORD_SEND {
        get {
            return ResourceManager.GetString("FORGOTTEN-PASSWORD-SEND", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tap Here.
    /// </summary>
    internal static string FORGOTTEN_PASSWORD_TAP {
        get {
            return ResourceManager.GetString("FORGOTTEN-PASSWORD-TAP", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search tree by name.
    /// </summary>
    internal static string IDENTIFY_TREE_NAME_TITLE {
        get {
            return ResourceManager.GetString("IDENTIFY-TREE-NAME-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search tree by region.
    /// </summary>
    internal static string IDENTIFY_TREE_REGION_TITLE {
        get {
            return ResourceManager.GetString("IDENTIFY-TREE-REGION-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search.
    /// </summary>
    internal static string IDENTIFY_TREE_SEARCHBAR_PLACEHOLER {
        get {
            return ResourceManager.GetString("IDENTIFY-TREE-SEARCHBAR-PLACEHOLER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Login.
    /// </summary>
    internal static string LOGIN_BUTTON {
        get {
            return ResourceManager.GetString("LOGIN-BUTTON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sorry, we failed to log in into your account, please check the mail and password fields..
    /// </summary>
    internal static string LOGIN_ERROR {
        get {
            return ResourceManager.GetString("LOGIN-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sorry, This user does not exists.
    /// </summary>
    internal static string LOGIN_ERROR_USER_NOT_FOUND {
        get {
            return ResourceManager.GetString("LOGIN-ERROR-USER-NOT-FOUND", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Mail.
    /// </summary>
    internal static string LOGIN_MAIL_PLACEHOLDER {
        get {
            return ResourceManager.GetString("LOGIN-MAIL-PLACEHOLDER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to To use this function, First you have to Sign-In in the app.
    /// </summary>
    internal static string LOGIN_MESSAGE {
        get {
            return ResourceManager.GetString("LOGIN-MESSAGE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Logged In?.
    /// </summary>
    internal static string LOGIN_MESSAGE_TITLE {
        get {
            return ResourceManager.GetString("LOGIN-MESSAGE-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Full Name.
    /// </summary>
    internal static string LOGIN_NAME_PLACEHOLDER {
        get {
            return ResourceManager.GetString("LOGIN-NAME-PLACEHOLDER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Password.
    /// </summary>
    internal static string LOGIN_PASSWORD_PLACEHOLDER {
        get {
            return ResourceManager.GetString("LOGIN-PASSWORD-PLACEHOLDER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Next.
    /// </summary>
    internal static string NEXT_BUTTON {
        get {
            return ResourceManager.GetString("NEXT-BUTTON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This email isn&apos;t verified yet.
    /// </summary>
    internal static string NOT_VERIFIED_ERROR {
        get {
            return ResourceManager.GetString("NOT-VERIFIED-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select Photo.
    /// </summary>
    internal static string Photo_Selector_ChoosePhoto {
        get {
            return ResourceManager.GetString("Photo-Selector-ChoosePhoto", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Take Photo.
    /// </summary>
    internal static string Photo_Selector_TakeePhoto {
        get {
            return ResourceManager.GetString("Photo-Selector-TakeePhoto", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sorry
    /// But we can&apos;t get the tree location, remember to have the camera activated in Privacy&gt; Location&gt; Camera, you can also select it manually with Google Maps.
    /// </summary>
    internal static string PHOTOLOCATION_ERROR {
        get {
            return ResourceManager.GetString("PHOTOLOCATION-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Register.
    /// </summary>
    internal static string REGISTER_BUTTON {
        get {
            return ResourceManager.GetString("REGISTER-BUTTON", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sorry, An unexpected error that we don&apos;t know has ocurred.
    /// </summary>
    internal static string REGISTER_ERROR_DEFAULT {
        get {
            return ResourceManager.GetString("REGISTER-ERROR-DEFAULT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Sorry but this email is already used.
    /// </summary>
    internal static string REGISTER_ERROR_EMAIL_USED {
        get {
            return ResourceManager.GetString("REGISTER-ERROR-EMAIL-USED", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please type a valid email.
    /// </summary>
    internal static string REGISTER_ERROR_INVALID_MAIL {
        get {
            return ResourceManager.GetString("REGISTER-ERROR-INVALID-MAIL", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please type a better password
    ///Remember that it has to be 8 characters minimum including letter and numbers.
    /// </summary>
    internal static string REGISTER_ERROR_WEAK_PASSWORD {
        get {
            return ResourceManager.GetString("REGISTER-ERROR-WEAK-PASSWORD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please, fill all the empty spaces.
    /// </summary>
    internal static string REGISTER_FIELDS_ERROR {
        get {
            return ResourceManager.GetString("REGISTER-FIELDS-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User created successfuly!
    ///Check your email to verify your account..
    /// </summary>
    internal static string REGISTER_USER_CREATED {
        get {
            return ResourceManager.GetString("REGISTER-USER-CREATED", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Save.
    /// </summary>
    internal static string SAVE {
        get {
            return ResourceManager.GetString("SAVE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Female.
    /// </summary>
    internal static string SEX_FEMALE {
        get {
            return ResourceManager.GetString("SEX-FEMALE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Male.
    /// </summary>
    internal static string SEX_MALE {
        get {
            return ResourceManager.GetString("SEX-MALE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Other.
    /// </summary>
    internal static string SEX_OTHER {
        get {
            return ResourceManager.GetString("SEX-OTHER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to With the Support of: .
    /// </summary>
    internal static string SUPPORT_OF {
        get {
            return ResourceManager.GetString("SUPPORT-OF", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Identify the species of a tree by selecting the color of its flowers.
    /// </summary>
    internal static string TOUCH_TUTORIAL_COLORS {
        get {
            return ResourceManager.GetString("TOUCH-TUTORIAL-COLORS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Average tree height:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_AVERAGE {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-AVERAGE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Flowering Days: .
    /// </summary>
    internal static string TREE_DETAILS_FORM_DAYS {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-DAYS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Depth:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_DEPTH {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-DEPTH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Flower dimensions:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_DIMENSIONS {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-DIMENSIONS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Main seed disperser:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_DISPERSER {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-DISPERSER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Height:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_HEIGTH {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-HEIGTH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Flowering months:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_MONTHS {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-MONTHS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tree origin:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_ORIGIN {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-ORIGIN", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Region:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_REGION {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-REGION", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This tree is presented by: .
    /// </summary>
    internal static string TREE_DETAILS_FORM_SPONSOR {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-SPONSOR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Width:.
    /// </summary>
    internal static string TREE_DETAILS_FORM_WIDTH {
        get {
            return ResourceManager.GetString("TREE-DETAILS-FORM-WIDTH", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Magical Trees.
    /// </summary>
    internal static string TREE_DETAILS_TITLE {
        get {
            return ResourceManager.GetString("TREE-DETAILS-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Supported apps to get the direction.
    /// </summary>
    internal static string TREE_FEED_MAPS_ACTIONSHEET_TITLE {
        get {
            return ResourceManager.GetString("TREE-FEED-MAPS-ACTIONSHEET-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Google Maps is necessary for getting the directions.
    /// </summary>
    internal static string TREE_FEED_MAPS_ERROR {
        get {
            return ResourceManager.GetString("TREE-FEED-MAPS-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select one tree.
    /// </summary>
    internal static string TREE_REPORT_ERROR_MESSAGE_SEARCH_TREE {
        get {
            return ResourceManager.GetString("TREE-REPORT-ERROR-MESSAGE-SEARCH-TREE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please provide all the information for the report.
    /// </summary>
    internal static string TREE_REPORT_ERROR_UPLOAD {
        get {
            return ResourceManager.GetString("TREE-REPORT-ERROR-UPLOAD", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to If you didn&apos;t find the tree in the list, you can write the name manually..
    /// </summary>
    internal static string TREE_REPORT_FIND_TREE_MESSAGE {
        get {
            return ResourceManager.GetString("TREE-REPORT-FIND-TREE-MESSAGE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Search the tree.
    /// </summary>
    internal static string TREE_REPORT_FIND_TREE_SEARCH_NAME {
        get {
            return ResourceManager.GetString("TREE-REPORT-FIND-TREE-SEARCH-NAME", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to What tree is it?.
    /// </summary>
    internal static string TREE_REPORT_FIND_TREE_TITLE {
        get {
            return ResourceManager.GetString("TREE-REPORT-FIND-TREE-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Write the name.
    /// </summary>
    internal static string TREE_REPORT_FIND_TREE_WRITE_NAME {
        get {
            return ResourceManager.GetString("TREE-REPORT-FIND-TREE-WRITE-NAME", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please select a location.
    /// </summary>
    internal static string TREE_REPORT_LOCATION_ERROR {
        get {
            return ResourceManager.GetString("TREE-REPORT-LOCATION-ERROR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tap on the location of the tree, the location will be more accurate if you zoom enough where you took the photo.
    /// </summary>
    internal static string TREE_REPORT_LOCATION_INSTRUCTION {
        get {
            return ResourceManager.GetString("TREE-REPORT-LOCATION-INSTRUCTION", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Instructions.
    /// </summary>
    internal static string TREE_REPORT_LOCATION_INSTRUCTION_TITLE {
        get {
            return ResourceManager.GetString("TREE-REPORT-LOCATION-INSTRUCTION-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Pick a location.
    /// </summary>
    internal static string TREE_REPORT_LOCATION_SELECT {
        get {
            return ResourceManager.GetString("TREE-REPORT-LOCATION-SELECT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Where did you take the picture?.
    /// </summary>
    internal static string TREE_REPORT_MAP_NAVIGATION_CONTROLLER_TITLE {
        get {
            return ResourceManager.GetString("TREE-REPORT-MAP-NAVIGATION-CONTROLLER-TITLE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select the photo.
    /// </summary>
    internal static string TREE_REPORT_PHOTO_SELECT {
        get {
            return ResourceManager.GetString("TREE-REPORT-PHOTO-SELECT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tree&apos;s flowering color?.
    /// </summary>
    internal static string TREE_REPORT_SELECT_COLOR {
        get {
            return ResourceManager.GetString("TREE-REPORT-SELECT-COLOR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Select the kind of tree.
    /// </summary>
    internal static string TREE_REPORT_TREE_SELECT {
        get {
            return ResourceManager.GetString("TREE-REPORT-TREE-SELECT", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Your report was uploaded successfuly!
    ///Once approved, you&apos;ll see it in the App!.
    /// </summary>
    internal static string TREE_REPORT_UPLOAD_SUCCESSFULY {
        get {
            return ResourceManager.GetString("TREE-REPORT-UPLOAD-SUCCESSFULY", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Use photo&apos;s Coordinates.
    /// </summary>
    internal static string TREE_REPORT_USER_COORDINATES {
        get {
            return ResourceManager.GetString("TREE-REPORT-USER-COORDINATES", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Use Maps.
    /// </summary>
    internal static string TREE_REPORT_USER_MAPS {
        get {
            return ResourceManager.GetString("TREE-REPORT-USER-MAPS", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to What&apos;s the name of the tree?.
    /// </summary>
    internal static string TREE_REPORT_WRITE_NAME_TREE {
        get {
            return ResourceManager.GetString("TREE-REPORT-WRITE-NAME-TREE", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Write the name here....
    /// </summary>
    internal static string TREE_REPORT_WRITE_NAME_TREE_PLACEHOLDER {
        get {
            return ResourceManager.GetString("TREE-REPORT-WRITE-NAME-TREE-PLACEHOLDER", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Explore and learn about different tree species by the color of their flowers..
    /// </summary>
    internal static string TUTORIAL_DESCRIPTION1 {
        get {
            return ResourceManager.GetString("TUTORIAL-DESCRIPTION1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ojeadores is a Magical Trees Foundation initiative, an organization that seeks to be a bridge of re connection between people and nature..
    /// </summary>
    internal static string TUTORIAL_DESCRIPTION2 {
        get {
            return ResourceManager.GetString("TUTORIAL-DESCRIPTION2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The Foundation has brought its educational programs to more than 5,000 children and youth, and has planted more than 25,000 trees..
    /// </summary>
    internal static string TUTORIAL_DESCRIPTION3 {
        get {
            return ResourceManager.GetString("TUTORIAL-DESCRIPTION3", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Ojeadores.
    /// </summary>
    internal static string TUTORIAL_TITLE1 {
        get {
            return ResourceManager.GetString("TUTORIAL-TITLE1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Reconnection.
    /// </summary>
    internal static string TUTORIAL_TITLE2 {
        get {
            return ResourceManager.GetString("TUTORIAL-TITLE2", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Magic Trees.
    /// </summary>
    internal static string TUTORIAL_TITLE3 {
        get {
            return ResourceManager.GetString("TUTORIAL-TITLE3", resourceCulture);
        }
    }
}
